@host=localhost
@port=4004
@protocol=http

### PUT operation ####

PUT {{protocol}}://{{host}}:{{port}}/media/MediaFile(2553a6d3-e860-47df-8354-e599db9dc953)/content HTTP/1.1
Content-Type: application/pdf
slug: SimpleInvoice.pdf

< ./SimpleInvoice.pdf

### create an empty object using POST ####

POST {{protocol}}://{{host}}:{{port}}/media/MediaFile HTTP/1.1
Content-Type: application/json

{}
### post operation V2 ####
POST {{protocol}}://{{host}}:{{port}}/v2/media/MediaFile HTTP/1.1
Content-Type: application/pdf
slug: SimpleInvoice.pdf

< ./SimpleInvoice.pdf